model:
  name: setr
  args:
    inp_size: 352
    loss: iou
    encoder_mode:
      name: dvp_p
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor