test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/acdc_valset/imgs
      root_path_2: ./load/acdc_valset/gt_label_mask
      cache: none
      split_key: test
      size: 352
  wrapper:
    name: val
    args:

      inp_size: 352
  batch_size: 4

eval_type: cod

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}


model:
  name: setr
  args:
    inp_size: 352
    loss: iou
    encoder_mode:
      name: dvp_p
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor